"""add_knowledge_models

Revision ID: 3ddf82e2fb46
Revises: 37755774077a
Create Date: 2026-06-19 19:26:32.630495

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3ddf82e2fb46'
down_revision: Union[str, None] = '37755774077a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ideas',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.Enum('BUSINESS', 'PRODUCT', 'CONTENT', 'PROJECT', 'INNOVATION', 'PERSONAL', 'OTHER', name='ideacategory'), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'EVALUATING', 'APPROVED', 'IN_DEVELOPMENT', 'IMPLEMENTED', 'REJECTED', name='ideastatus'), nullable=False),
    sa.Column('impact_score', sa.Integer(), nullable=False),
    sa.Column('effort_score', sa.Integer(), nullable=False),
    sa.Column('confidence_score', sa.Integer(), nullable=False),
    sa.Column('priority_score', sa.Integer(), nullable=False),
    sa.Column('problem_solved', sa.Text(), nullable=True),
    sa.Column('target_audience', sa.String(length=300), nullable=True),
    sa.Column('resources_needed', sa.JSON(), nullable=False),
    sa.Column('risks', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ideas_id'), 'ideas', ['id'], unique=False)
    op.create_index(op.f('ix_ideas_user_id'), 'ideas', ['user_id'], unique=False)
    op.create_table('journal_entries',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('entry_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('mood', sa.Enum('TERRIBLE', 'BAD', 'OKAY', 'GOOD', 'AMAZING', name='moodlevel'), nullable=True),
    sa.Column('mood_score', sa.Integer(), nullable=True),
    sa.Column('energy_level', sa.Integer(), nullable=True),
    sa.Column('stress_level', sa.Integer(), nullable=True),
    sa.Column('gratitude', sa.JSON(), nullable=False),
    sa.Column('intentions', sa.JSON(), nullable=False),
    sa.Column('accomplishments', sa.JSON(), nullable=False),
    sa.Column('lessons_learned', sa.Text(), nullable=True),
    sa.Column('weather', sa.Enum('SUNNY', 'CLOUDY', 'RAINY', 'SNOWY', 'STORMY', 'FOGGY', name='weathertype'), nullable=True),
    sa.Column('location', sa.String(length=200), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('is_private', sa.Boolean(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_journal_entries_entry_date'), 'journal_entries', ['entry_date'], unique=False)
    op.create_index(op.f('ix_journal_entries_id'), 'journal_entries', ['id'], unique=False)
    op.create_index(op.f('ix_journal_entries_user_id'), 'journal_entries', ['user_id'], unique=False)
    op.create_table('learnings',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('instructor', sa.String(length=200), nullable=True),
    sa.Column('provider', sa.String(length=200), nullable=True),
    sa.Column('url', sa.String(length=500), nullable=True),
    sa.Column('learning_type', sa.Enum('COURSE', 'BOOK', 'TUTORIAL', 'VIDEO', 'PODCAST', 'ARTICLE', 'WORKSHOP', 'CERTIFICATION', 'OTHER', name='learningtype'), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('skills', sa.JSON(), nullable=False),
    sa.Column('status', sa.Enum('WISHLIST', 'IN_PROGRESS', 'COMPLETED', 'PAUSED', 'ABANDONED', name='learningstatus'), nullable=False),
    sa.Column('progress', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('total_hours', sa.Float(), nullable=True),
    sa.Column('hours_spent', sa.Float(), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=True),
    sa.Column('completed_date', sa.Date(), nullable=True),
    sa.Column('cost', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('key_takeaways', sa.JSON(), nullable=False),
    sa.Column('certificate_url', sa.String(length=500), nullable=True),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_learnings_category'), 'learnings', ['category'], unique=False)
    op.create_index(op.f('ix_learnings_id'), 'learnings', ['id'], unique=False)
    op.create_index(op.f('ix_learnings_user_id'), 'learnings', ['user_id'], unique=False)
    op.create_table('notes',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('folder', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('color', sa.Enum('DEFAULT', 'YELLOW', 'GREEN', 'BLUE', 'RED', 'PURPLE', 'ORANGE', 'PINK', name='notecolor'), nullable=False),
    sa.Column('is_pinned', sa.Boolean(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('attachments', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notes_folder'), 'notes', ['folder'], unique=False)
    op.create_index(op.f('ix_notes_id'), 'notes', ['id'], unique=False)
    op.create_index(op.f('ix_notes_is_pinned'), 'notes', ['is_pinned'], unique=False)
    op.create_index(op.f('ix_notes_user_id'), 'notes', ['user_id'], unique=False)
    op.create_table('wikis',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('slug', sa.String(length=300), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('excerpt', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('view_count', sa.Integer(), nullable=False),
    sa.Column('word_count', sa.Integer(), nullable=False),
    sa.Column('is_published', sa.Boolean(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['wikis.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_wikis_category'), 'wikis', ['category'], unique=False)
    op.create_index(op.f('ix_wikis_id'), 'wikis', ['id'], unique=False)
    op.create_index(op.f('ix_wikis_parent_id'), 'wikis', ['parent_id'], unique=False)
    op.create_index(op.f('ix_wikis_slug'), 'wikis', ['slug'], unique=False)
    op.create_index(op.f('ix_wikis_user_id'), 'wikis', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wikis_user_id'), table_name='wikis')
    op.drop_index(op.f('ix_wikis_slug'), table_name='wikis')
    op.drop_index(op.f('ix_wikis_parent_id'), table_name='wikis')
    op.drop_index(op.f('ix_wikis_id'), table_name='wikis')
    op.drop_index(op.f('ix_wikis_category'), table_name='wikis')
    op.drop_table('wikis')
    op.drop_index(op.f('ix_notes_user_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_is_pinned'), table_name='notes')
    op.drop_index(op.f('ix_notes_id'), table_name='notes')
    op.drop_index(op.f('ix_notes_folder'), table_name='notes')
    op.drop_table('notes')
    op.drop_index(op.f('ix_learnings_user_id'), table_name='learnings')
    op.drop_index(op.f('ix_learnings_id'), table_name='learnings')
    op.drop_index(op.f('ix_learnings_category'), table_name='learnings')
    op.drop_table('learnings')
    op.drop_index(op.f('ix_journal_entries_user_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_id'), table_name='journal_entries')
    op.drop_index(op.f('ix_journal_entries_entry_date'), table_name='journal_entries')
    op.drop_table('journal_entries')
    op.drop_index(op.f('ix_ideas_user_id'), table_name='ideas')
    op.drop_index(op.f('ix_ideas_id'), table_name='ideas')
    op.drop_table('ideas')
    # ### end Alembic commands ###
