"""add_life_models

Revision ID: ce4abd19e1eb
Revises: 3ddf82e2fb46
Create Date: 2026-06-19 19:28:57.209231

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ce4abd19e1eb'
down_revision: Union[str, None] = '3ddf82e2fb46'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('financial_accounts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('account_type', sa.Enum('CHECKING', 'SAVINGS', 'CASH', 'CREDIT_CARD', 'INVESTMENT', 'LOAN', 'CRYPTO', 'OTHER', name='accounttype'), nullable=False),
    sa.Column('institution', sa.String(length=200), nullable=True),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('initial_balance', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('credit_limit', sa.Float(), nullable=True),
    sa.Column('interest_rate', sa.Float(), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('icon', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('include_in_total', sa.Boolean(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_financial_accounts_id'), 'financial_accounts', ['id'], unique=False)
    op.create_index(op.f('ix_financial_accounts_user_id'), 'financial_accounts', ['user_id'], unique=False)
    op.create_table('health_logs',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('metric_type', sa.Enum('WEIGHT', 'BODY_FAT', 'MUSCLE_MASS', 'BMI', 'BLOOD_PRESSURE', 'HEART_RATE', 'BLOOD_SUGAR', 'STEPS', 'DISTANCE', 'CALORIES_BURNED', 'EXERCISE_MINUTES', 'WORKOUT', 'WATER', 'CALORIES_CONSUMED', 'PROTEIN', 'CARBS', 'FATS', 'MEAL', 'SLEEP_HOURS', 'SLEEP_QUALITY', 'MOOD', 'ENERGY', 'STRESS', 'MEDITATION_MINUTES', 'MEDICATION', 'SYMPTOM', 'OTHER', name='metrictype'), nullable=False),
    sa.Column('log_date', sa.Date(), nullable=False),
    sa.Column('value', sa.Float(), nullable=True),
    sa.Column('value_text', sa.String(length=500), nullable=True),
    sa.Column('unit', sa.String(length=50), nullable=True),
    sa.Column('extra_data', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_health_logs_id'), 'health_logs', ['id'], unique=False)
    op.create_index(op.f('ix_health_logs_log_date'), 'health_logs', ['log_date'], unique=False)
    op.create_index(op.f('ix_health_logs_metric_type'), 'health_logs', ['metric_type'], unique=False)
    op.create_index(op.f('ix_health_logs_user_id'), 'health_logs', ['user_id'], unique=False)
    op.create_table('vision_boards',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('affirmation', sa.Text(), nullable=True),
    sa.Column('image_url', sa.String(length=500), nullable=True),
    sa.Column('color', sa.String(length=20), nullable=False),
    sa.Column('category', sa.Enum('CAREER', 'HEALTH', 'WEALTH', 'RELATIONSHIPS', 'TRAVEL', 'PERSONAL_GROWTH', 'LIFESTYLE', 'CREATIVE', 'SPIRITUAL', 'OTHER', name='visioncategory'), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('target_date', sa.Date(), nullable=True),
    sa.Column('is_achieved', sa.Boolean(), nullable=False),
    sa.Column('achieved_at', sa.Date(), nullable=True),
    sa.Column('position_x', sa.Integer(), nullable=False),
    sa.Column('position_y', sa.Integer(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('is_favorite', sa.Boolean(), nullable=False),
    sa.Column('is_archived', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_vision_boards_id'), 'vision_boards', ['id'], unique=False)
    op.create_index(op.f('ix_vision_boards_user_id'), 'vision_boards', ['user_id'], unique=False)
    op.create_table('transactions',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('transaction_type', sa.Enum('INCOME', 'EXPENSE', 'TRANSFER', 'INVESTMENT', name='transactiontype'), nullable=False),
    sa.Column('category', sa.Enum('SALARY', 'FREELANCE', 'BUSINESS', 'INVESTMENT_RETURN', 'GIFT', 'REFUND', 'FOOD', 'GROCERIES', 'TRANSPORTATION', 'HOUSING', 'UTILITIES', 'ENTERTAINMENT', 'SHOPPING', 'HEALTHCARE', 'EDUCATION', 'SUBSCRIPTIONS', 'INSURANCE', 'TRAVEL', 'PERSONAL_CARE', 'SAVINGS', 'DEBT_PAYMENT', 'TAXES', 'CHARITY', 'OTHER', name='transactioncategory'), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('merchant', sa.String(length=200), nullable=True),
    sa.Column('transaction_date', sa.Date(), nullable=False),
    sa.Column('tags', sa.JSON(), nullable=False),
    sa.Column('is_recurring', sa.Boolean(), nullable=False),
    sa.Column('recurrence_pattern', sa.String(length=50), nullable=True),
    sa.Column('receipt_url', sa.String(length=500), nullable=True),
    sa.Column('transfer_account_id', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['financial_accounts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['transfer_account_id'], ['financial_accounts.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_transactions_account_id'), 'transactions', ['account_id'], unique=False)
    op.create_index(op.f('ix_transactions_category'), 'transactions', ['category'], unique=False)
    op.create_index(op.f('ix_transactions_id'), 'transactions', ['id'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_date'), 'transactions', ['transaction_date'], unique=False)
    op.create_index(op.f('ix_transactions_transaction_type'), 'transactions', ['transaction_type'], unique=False)
    op.create_index(op.f('ix_transactions_user_id'), 'transactions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_transactions_user_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_type'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_transaction_date'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_id'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_category'), table_name='transactions')
    op.drop_index(op.f('ix_transactions_account_id'), table_name='transactions')
    op.drop_table('transactions')
    op.drop_index(op.f('ix_vision_boards_user_id'), table_name='vision_boards')
    op.drop_index(op.f('ix_vision_boards_id'), table_name='vision_boards')
    op.drop_table('vision_boards')
    op.drop_index(op.f('ix_health_logs_user_id'), table_name='health_logs')
    op.drop_index(op.f('ix_health_logs_metric_type'), table_name='health_logs')
    op.drop_index(op.f('ix_health_logs_log_date'), table_name='health_logs')
    op.drop_index(op.f('ix_health_logs_id'), table_name='health_logs')
    op.drop_table('health_logs')
    op.drop_index(op.f('ix_financial_accounts_user_id'), table_name='financial_accounts')
    op.drop_index(op.f('ix_financial_accounts_id'), table_name='financial_accounts')
    op.drop_table('financial_accounts')
    # ### end Alembic commands ###
